// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-4MRg6g4zfv4cIk8oKiU3Y86OQ5rscmo',
    appId: '1:634779855933:web:f909c3efb62b6651850e54',
    messagingSenderId: '634779855933',
    projectId: 'aqua-conecta',
    authDomain: 'aqua-conecta.firebaseapp.com',
    storageBucket: 'aqua-conecta.appspot.com',
    measurementId: 'G-BZN80JGB7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT760_lDQHEPewiVbPO3e6k1X5fuX2Y4M',
    appId: '1:634779855933:android:d72471f26f5a9d1f850e54',
    messagingSenderId: '634779855933',
    projectId: 'aqua-conecta',
    storageBucket: 'aqua-conecta.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdlxNSCc0p3AQW-QBUpMDCox73YVQrV9c',
    appId: '1:634779855933:ios:e45bf1ae0c1c0a01850e54',
    messagingSenderId: '634779855933',
    projectId: 'aqua-conecta',
    storageBucket: 'aqua-conecta.appspot.com',
    iosBundleId: 'com.example.aquaConecta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdlxNSCc0p3AQW-QBUpMDCox73YVQrV9c',
    appId: '1:634779855933:ios:e45bf1ae0c1c0a01850e54',
    messagingSenderId: '634779855933',
    projectId: 'aqua-conecta',
    storageBucket: 'aqua-conecta.appspot.com',
    iosBundleId: 'com.example.aquaConecta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-4MRg6g4zfv4cIk8oKiU3Y86OQ5rscmo',
    appId: '1:634779855933:web:8d52993cbd45af5d850e54',
    messagingSenderId: '634779855933',
    projectId: 'aqua-conecta',
    authDomain: 'aqua-conecta.firebaseapp.com',
    storageBucket: 'aqua-conecta.appspot.com',
    measurementId: 'G-WMNTSVY9XQ',
  );

}